FROM maven:3.6.3-openjdk-8 as BUILD
COPY sus /usr/src/myapp/sus
COPY is /usr/src/myapp/is
COPY common /usr/src/myapp/common
COPY autotest /usr/src/myapp/autotest
COPY pom.xml /usr/src/myapp
RUN mvn -f /usr/src/myapp/pom.xml clean package -am -pl :is

FROM openjdk:8-jre
WORKDIR /opt/
COPY --from=BUILD /usr/src/myapp/is/target/is.jar .
EXPOSE 8080
CMD ["java","-Xms512m","-Xmx1g","-jar","is.jar"]
